'use client'

import { useState } from 'react'
import useSWR from 'swr'
import { CalendarDays, Cloud, Lightbulb, Link2, Save, Settings2, Sparkles, Target, FolderKanban } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { createClient } from '@/lib/supabase/client'
import { useFinancialSnapshot } from '@/hooks/use-financial-snapshot'
import { formatBRL } from '@/lib/mock-data'

const modules: Record<string, { title: string; description: string; icon: typeof CalendarDays }> = {
  agenda: { title: 'Agenda', description: 'Compromissos e vencimentos em contexto.', icon: CalendarDays },
  projetos: { title: 'Projetos', description: 'Iniciativas e tarefas do seu workspace.', icon: FolderKanban },
  drive: { title: 'Drive', description: 'Metadados de arquivos vinculados ao workspace.', icon: Cloud },
  insights: { title: 'KEVO Insights', description: 'Sinais determinísticos calculados dos seus dados.', icon: Lightbulb },
  plano: { title: 'Plano', description: 'Status comercial e acesso da sua conta.', icon: Target },
  integrações: { title: 'Integrações', description: 'Conexões disponíveis e estado real de configuração.', icon: Link2 },
  configurações: { title: 'Configurações', description: 'Perfil e preferências persistidas.', icon: Settings2 },
  planilhas: { title: 'KEVO Sheets', description: 'Visão tabular das movimentações persistidas.', icon: Sparkles },
}

function Layout({ title, description, children, Icon }: { title: string; description: string; children: React.ReactNode; Icon: typeof CalendarDays }) {
  return <main className="mx-auto max-w-[1500px] p-4 sm:p-7"><div className="mb-8"><div className="mb-2 text-[10px] uppercase tracking-[0.18em] text-primary">KEVO / Workspace</div><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center border border-primary/25 bg-primary/10"><Icon className="size-5 text-primary" /></div><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div></div>{children}</main>
}

function EmptyState({ text, detail }: { text: string; detail: string }) { return <Card className="border-dashed bg-card/40 shadow-none"><CardContent className="flex min-h-[280px] flex-col items-center justify-center gap-2 text-center"><div className="text-sm font-medium">{text}</div><p className="max-w-md text-xs leading-5 text-muted-foreground">{detail}</p></CardContent></Card> }

function Insights() { const { summary, data, loading, error } = useFinancialSnapshot('30D'); if (loading) return <p className="text-sm text-muted-foreground">Calculando sinais…</p>; if (error) return <p className="text-sm text-destructive">Não foi possível calcular os sinais.</p>; if (!data || !data.transactions.length) return <EmptyState text="Ainda não há sinais para calcular" detail="Registre movimentações, configure um orçamento ou crie uma meta para receber leituras objetivas do seu histórico." />; const expenseShare = summary?.expenses ? Math.round((data.transactions.filter((row) => row.type === 'expense').length / data.transactions.length) * 100) : 0; return <div className="grid gap-4 sm:grid-cols-2"><Card className="bg-card/70 shadow-none"><CardContent className="p-5"><div className="text-xs font-medium">Resultado dos últimos 30 dias</div><div className="mt-3 text-2xl font-semibold">{formatBRL(summary?.result ?? 0)}</div><p className="mt-2 text-xs text-muted-foreground">Sinal calculado diretamente do ledger persistido.</p></CardContent></Card><Card className="bg-card/70 shadow-none"><CardContent className="p-5"><div className="text-xs font-medium">Participação de despesas</div><div className="mt-3 text-2xl font-semibold">{expenseShare}%</div><p className="mt-2 text-xs text-muted-foreground">Proporção de registros classificados como despesa.</p></CardContent></Card><Card className="border-dashed bg-card/40 shadow-none sm:col-span-2"><CardContent className="p-5"><div className="text-xs font-medium">KEVO Intelligence</div><p className="mt-2 text-xs text-muted-foreground">Em breve. Os sinais acima são determinísticos e não representam uma recomendação de IA.</p></CardContent></Card></div> }

function Plan() { const { data, error, isLoading } = useSWR('kevo-subscription', async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('AUTH_REQUIRED'); const result = await supabase.from('subscriptions').select('plan,status,purchased_at,expires_at,source').eq('user_id', user.id).order('created_at', { ascending: false }).limit(1).maybeSingle(); if (result.error) throw result.error; return result.data }); if (isLoading) return <p className="text-sm text-muted-foreground">Consultando plano…</p>; if (error) return <p className="text-sm text-destructive">Não foi possível consultar o plano.</p>; if (!data) return <EmptyState text="Nenhum plano comercial vinculado" detail="Seu acesso comercial será exibido aqui quando uma autorização válida for associada à sua conta." />; return <Card className="max-w-xl bg-card/70 shadow-none"><CardContent className="space-y-4 p-5 text-sm"><div className="flex items-center justify-between"><span className="text-muted-foreground">Plano</span><strong>{data.plan}</strong></div><div className="flex items-center justify-between"><span className="text-muted-foreground">Status</span><strong className={data.status === 'active' ? 'text-primary' : 'text-muted-foreground'}>{data.status === 'active' ? 'Ativo' : 'Inativo'}</strong></div>{data.purchased_at && <div className="flex items-center justify-between"><span className="text-muted-foreground">Compra</span><span>{new Date(data.purchased_at).toLocaleDateString('pt-BR')}</span></div>}</CardContent></Card> }

function Settings() { const profile = useSWR('kevo-profile', async () => { const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('AUTH_REQUIRED'); const result = await supabase.from('profiles').select('first_name,last_name,preferences').eq('id', user.id).maybeSingle(); if (result.error) throw result.error; return { user, profile: result.data } }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [name, setName] = useState(''); const save = async () => { if (!profile.data?.user) return; setSaving(true); const supabase = createClient(); const { error } = await supabase.from('profiles').update({ first_name: name }).eq('id', profile.data.user.id); setSaving(false); setMessage(error ? 'Não foi possível salvar.' : 'Perfil salvo.'); if (!error) profile.mutate() }; if (profile.isLoading) return <p className="text-sm text-muted-foreground">Carregando perfil…</p>; if (profile.error) return <p className="text-sm text-destructive">Não foi possível carregar o perfil.</p>; return <Card className="max-w-xl bg-card/70 shadow-none"><CardContent className="space-y-4 p-5"><div><label className="text-xs text-muted-foreground" htmlFor="kevo-name">Nome</label><input id="kevo-name" value={name || profile.data?.profile?.first_name || ''} onChange={(event) => setName(event.target.value)} className="mt-2 w-full border border-border bg-background px-3 py-2 text-sm outline-none focus:border-primary" /></div><div className="text-xs text-muted-foreground">E-mail: {profile.data?.user.email}</div><Button onClick={save} disabled={saving}><Save data-icon="inline-start" />{saving ? 'Salvando…' : 'Salvar perfil'}</Button>{message && <p role="status" className="text-xs text-primary">{message}</p>}</CardContent></Card> }

export function KevoModule({ active }: { active: string }) { const item = modules[active] ?? modules.insights; const Icon = item.icon; const content = active === 'insights' ? <Insights /> : active === 'plano' ? <Plan /> : active === 'configurações' ? <Settings /> : <EmptyState text={active === 'integrações' ? 'Nenhuma integração conectada' : active === 'drive' ? 'Nenhum arquivo disponível' : active === 'agenda' ? 'Nenhum compromisso registrado' : active === 'projetos' ? 'Nenhum projeto registrado' : 'Nenhuma movimentação disponível'} detail={active === 'integrações' ? 'Conectores serão exibidos somente após confirmação real da integração.' : 'Este estado reflete os dados persistidos da sua conta. Use os módulos financeiros para começar, sem conteúdo demonstrativo.'} />; return <Layout title={item.title} description={item.description} Icon={Icon}>{content}</Layout> }
