'use client'

import { useMemo, useState } from 'react'
import { Check, Plus, Search, Trash2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useFinanceTable } from '@/hooks/use-finance-table'
import type { FinanceTable } from '@/services/finance-repository'
import { useTransactions } from '@/hooks/use-transactions'
import { useFinancialSnapshot } from '@/hooks/use-financial-snapshot'
import { formatBRL } from '@/lib/mock-data'

const config: Record<string, { table: FinanceTable; title: string; description: string; name: string; amount?: string }> = {
  categorias: { table: 'categories', title: 'Categorias', description: 'Organize seus gastos com dados persistidos.', name: 'Nome' },
  contas: { table: 'accounts', title: 'Contas', description: 'Contas reais, saldos e movimentações vinculadas.', name: 'Nome', amount: 'Saldo' },
  orçamentos: { table: 'budgets', title: 'Orçamentos', description: 'Acompanhe limites e utilização por período.', name: 'Nome', amount: 'Limite' },
  metas: { table: 'goals', title: 'Metas', description: 'Acompanhe progresso e prazos financeiros.', name: 'Nome', amount: 'Objetivo' },
  agenda: { table: 'bills', title: 'Contas a pagar', description: 'Vencimentos próximos, atrasados e pagos.', name: 'Descrição', amount: 'Valor' },
}

function Header({ title, description, onAdd }: { title: string; description: string; onAdd: () => void }) { return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 text-[10px] uppercase tracking-[0.18em] text-primary">KEVO / Financial Core</div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><Button size="sm" onClick={onAdd}><Plus data-icon="inline-start" />Novo registro</Button></div> }
function Toast({ message, onClose }: { message: string; onClose: () => void }) { return <div role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-3 border border-primary/30 bg-card px-4 py-3 text-xs shadow-xl"><Check className="size-4 text-primary" />{message}<button onClick={onClose} aria-label="Fechar aviso"><X className="size-3" /></button></div> }

function FinanceWorkspace({ active }: { active: string }) {
  const item = config[active]
  const store = useFinanceTable(item.table)
  const [search, setSearch] = useState('')
  const [toast, setToast] = useState<string | null>(null)
  const filtered = useMemo(() => store.data.filter((row: any) => String(row.name ?? row.title ?? '').toLowerCase().includes(search.toLowerCase())), [store.data, search])
  const add = async () => { try { await store.create(item.table === 'goals' ? { name: 'Nova meta', target_amount: 0, current_amount: 0 } : item.table === 'bills' ? { name: 'Nova conta', amount: 0, due_date: new Date().toISOString().slice(0, 10), status: 'upcoming' } : item.table === 'budgets' ? { name: 'Novo orçamento', limit_amount: 0, period: 'monthly' } : item.table === 'accounts' ? { name: 'Nova conta', type: 'checking', balance: 0 } : { name: 'Nova categoria' }); setToast('Registro criado.'); } catch (error) { setToast(error instanceof Error ? error.message : 'Não foi possível criar.') } }
  return <><Header title={item.title} description={item.description} onAdd={add} /><Card className="border-border/80 bg-card/70 shadow-none"><CardHeader className="flex-row items-center justify-between gap-3"><CardTitle className="text-sm">Dados persistidos</CardTitle><label className="flex items-center gap-2 border border-border px-3 py-2 text-xs"><Search className="size-3 text-muted-foreground" /><input aria-label={`Buscar ${item.title}`} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar" className="w-36 bg-transparent outline-none placeholder:text-muted-foreground" /></label></CardHeader><CardContent>{store.loading ? <div className="py-16 text-center text-xs text-muted-foreground">Carregando…</div> : store.error ? <div className="py-16 text-center text-xs text-destructive">{store.error}</div> : filtered.length === 0 ? <div className="flex min-h-[260px] flex-col items-center justify-center gap-2 text-center"><div className="text-sm font-medium">Nenhum registro ainda</div><p className="text-xs text-muted-foreground">Crie o primeiro registro para começar a acompanhar este módulo.</p><Button variant="outline" size="sm" onClick={add}><Plus data-icon="inline-start" />Criar agora</Button></div> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-[10px] text-muted-foreground"><tr className="border-b border-border"><th className="px-3 py-3">{item.name}</th>{item.amount && <th className="px-3 py-3 text-right">{item.amount}</th>}<th className="px-3 py-3">Atualizado</th><th className="px-3 py-3 text-right">Ações</th></tr></thead><tbody>{filtered.map((row: any) => <tr key={row.id} className="border-b border-border/60"><td className="px-3 py-3 font-medium">{row.name}</td>{item.amount && <td className="px-3 py-3 text-right">{formatBRL(Number(row.balance ?? row.limit_amount ?? row.target_amount ?? row.amount ?? 0))}</td>}<td className="px-3 py-3 text-muted-foreground">{new Date(row.updated_at ?? row.created_at).toLocaleDateString('pt-BR')}</td><td className="px-3 py-3 text-right"><button aria-label={`Excluir ${row.name}`} className="text-muted-foreground hover:text-destructive" onClick={async () => { try { await store.remove(row.id); setToast('Registro excluído.') } catch (error) { setToast(error instanceof Error ? error.message : 'Não foi possível excluir.') } }}><Trash2 className="size-4" /></button></td></tr>)}</tbody></table></div>}</CardContent></Card>{toast && <Toast message={toast} onClose={() => setToast(null)} />}</>
}

function TransactionsWorkspace() { const { data, loading, error } = useTransactions(); return <><Header title="Movimentações" description="Ledger real, filtrável e sincronizado com o Supabase." onAdd={() => undefined} /><Card className="border-border/80 bg-card/70 shadow-none"><CardContent>{loading ? <div className="py-16 text-center text-xs text-muted-foreground">Carregando…</div> : error ? <div className="py-16 text-center text-xs text-destructive">{error}</div> : data.length === 0 ? <div className="py-16 text-center text-xs text-muted-foreground">Nenhuma movimentação persistida ainda.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="text-[10px] text-muted-foreground"><tr className="border-b border-border"><th className="px-3 py-3">Data</th><th className="px-3 py-3">Descrição</th><th className="px-3 py-3 text-right">Valor</th></tr></thead><tbody>{data.map((row) => <tr key={row.id} className="border-b border-border/60"><td className="px-3 py-3">{row.transaction_date}</td><td className="px-3 py-3">{row.description}</td><td className="px-3 py-3 text-right">{formatBRL(Number(row.amount))}</td></tr>)}</tbody></table></div>}</CardContent></Card></> }

function ActivityWorkspace({ active }: { active: string }) { const { data, loading, error } = useFinancialSnapshot('1A'); const title = active === 'relatórios' ? 'Relatórios' : 'Timeline'; if (loading) return <Header title={title} description="Consolidando dados reais do seu workspace." onAdd={() => undefined} />; if (error) return <><Header title={title} description="Não foi possível consolidar os dados." onAdd={() => undefined} /><p className="text-sm text-destructive">{error.message}</p></>; const items = [...(data?.transactions ?? []).map((row) => ({ id: `transaction-${row.id}`, date: row.transaction_date, label: row.description, detail: row.type === 'income' ? 'Receita' : 'Despesa', amount: Number(row.amount) })), ...(data?.bills ?? []).map((row) => ({ id: `bill-${row.id}`, date: String(row.due_date), label: String(row.name), detail: 'Conta a pagar', amount: Number(row.amount ?? 0) }))].sort((a, b) => b.date.localeCompare(a.date)); return <><Header title={title} description="Leitura baseada exclusivamente nos seus dados persistidos." onAdd={() => undefined} /><Card className="border-border/80 bg-card/70 shadow-none"><CardContent className="p-0">{items.length === 0 ? <div className="py-16 text-center text-xs text-muted-foreground">Nenhum evento financeiro para exibir ainda.</div> : <div className="divide-y divide-border/60">{items.slice(0, 50).map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-5 py-4 text-xs"><div><div className="font-medium">{item.label}</div><div className="mt-1 text-muted-foreground">{item.date} · {item.detail}</div></div><span>{formatBRL(Math.abs(item.amount))}</span></div>)}</div>}</CardContent></Card></> }

export function ModuleWorkspace({ active }: { active: string }) { const content = active === 'movimentações' ? <TransactionsWorkspace /> : config[active] ? <FinanceWorkspace active={active} /> : active === 'relatórios' || active === 'timeline' ? <ActivityWorkspace active={active} /> : <div className="flex min-h-[360px] items-center justify-center text-sm text-muted-foreground">Este módulo será conectado aos dados reais nas próximas etapas.</div>; return <main className="mx-auto max-w-[1500px] p-4 sm:p-7">{content}</main> }
